<?php
/**
 * @file
 * Installation functions for the drealty image field.
 */

function drealty_image_field_schema($field) {
  $columns = array(
      'url' => array(
          'description' => 'The url where the image is located.',
          'type' => 'varchar',
          'length' => 255,
          'default' => '',
          'not null' => FALSE,
      ),
  );

  return array('columns' => $columns);
}