<?php

/** File
 * 
 */

function drealty_lead_entity_info(){
	$entities = array();
	
  $entities['drealty_lead'] = array(
		'label' => t('Drealty Lead'),
		'plural label' => t('Drealty Leads'),
		'entity class' => 'DrealtyLead',
		'controller class' => 'DrealtyLeadController',
		'token type' => 'drealty_lead',
		'base table' => 'drealty_lead',
		'uri callback' => 'entity_class_uri',
		'exportable' => FALSE,
		'fieldable' => TRUE,
		'admin ui' => array(
			'path' => 'admin/drealty/drealty_lead',
			'file' => 'includes/drealty_lead.lead.admin.inc',
			'controller class' => 'DrealtyLeadUIController',
			'menu wildcard' => '%drealty_lead',
		),
    'bundles' => array(
      'drealty_lead' => array(
        'label' => 'Drealty Lead',
      ),
    ),
		'entity keys' => array(
			'id' => 'id',
		),
		'module' => 'drealty_lead',
		'access callback' => 'drealty_lead_access',
  );
  
  return $entities;
}

/**
 * Implements hook_permission().
 */
function drealty_lead_permission() {
  $permissions = array(
		'administer drealty leads' => array(
      'title' => t('Administer dRealty Leads'),
    ),
		'view drealty leads' => array(
      'title' => t('View dRealty Leads'),
    ),
		'create drealty leads' => array(
      'title' => t('Create dRealty Leads'),
    ),
		'edit drealty leads' => array(
      'title' => t('Edit dRealty Leads'),
    ),
		'delete drealty leads' => array(
      'title' => t('Delete dRealty Leads'),
    ),
  );

  return $permissions;
}

function drealty_lead_access($op, $listing = NULL, $account = NULL) {
  if (user_access('administer drealty leads', $account)) {
    return TRUE;
  }
	
	if ($op == 'create' || $op == 'update') {
    $op = 'edit';
  }

  $access = module_invoke_all('drealty_lead_access', $op, $listing, $account);

  // Only grant access if at least one module granted access and no one denied
  // access.
	
  if (in_array(FALSE, $access, TRUE)) {
    return FALSE;
  } elseif (in_array(TRUE, $access, TRUE)) {
    return TRUE;
  }
	
  return FALSE;
}

function drealty_lead_create($values = array()) {
  return entity_get_controller('drealty_lead')->create($values);
}

function drealty_lead_uri(DrealtyLead $lead) {
  return array('path' => 'drealty_lead/' . $lead->id);
}

function drealty_lead_load($id, $conditions = array(), $reset = FALSE) {
  $ids = (isset($id) ? array($id) : array());
  $entity = drealty_lead_load_multiple($ids, $conditions, $reset);
  return $entity ? reset($entity) : FALSE;
}

function drealty_lead_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('drealty_lead', $ids, $conditions, $reset);
}