<?php

/** File
 * 
 */

function drealty_lead_entity_info(){
	$entities = array();
	
  $entities['drealty_lead'] = array(
		'label' => t('Drealty Lead'),
		'plural label' => t('Drealty Leads'),
		'entity class' => 'DrealtyLead',
		'controller class' => 'DrealtyLeadController',
		'token type' => 'drealty_lead',
		'base table' => 'drealty_lead',
		'uri callback' => 'entity_class_uri',
		'exportable' => FALSE,
		'fieldable' => TRUE,
		'bundles' => array(
			'drealty_lead' => array(
				'label' => t('Drealty Lead'),
				'admin' => array(
					'path' => 'admin/drealty/drealty-lead/manage/drealty_lead',
					'real path' => 'admin/drealty/drealty-lead/manage/drealty-lead',
					'bundle argument' => 4,
					'access arguments' => array('administer drealty leads'),
				),
			),
		),
		'admin ui' => array(
			'path' => 'admin/content/drealty-lead',
			'file' => 'includes/drealty_lead.lead.admin.inc',
			'controller class' => 'DrealtyLeadUIController',
			'menu wildcard' => '%drealty_lead',
		),
		'entity keys' => array(
			'id' => 'id',
		),
		'module' => 'drealty_lead',
		'access callback' => 'drealty_lead_access',
  );
  
  return $entities;
}

/**
 * Implements hook_permission().
 */
function drealty_lead_permission() {
  $permissions = array(
		'administer drealty leads' => array(
      'title' => t('Administer dRealty Leads'),
    ),
		'view drealty leads' => array(
      'title' => t('View dRealty Leads'),
    ),
		'create drealty leads' => array(
      'title' => t('Create dRealty Leads'),
    ),
		'edit drealty leads' => array(
      'title' => t('Edit dRealty Leads'),
    ),
		'delete drealty leads' => array(
      'title' => t('Delete dRealty Leads'),
    ),
  );

  return $permissions;
}

function drealty_lead_access($op, $listing = NULL, $account = NULL) {
  if (user_access('administer drealty leads', $account)) {
    return TRUE;
  }
	
	if ($op == 'create' || $op == 'update') {
    $op = 'edit';
  }

  $access = module_invoke_all('drealty_lead_access', $op, $listing, $account);

  // Only grant access if at least one module granted access and no one denied
  // access.
	
  if (in_array(FALSE, $access, TRUE)) {
    return FALSE;
  } elseif (in_array(TRUE, $access, TRUE)) {
    return TRUE;
  }
	
  return FALSE;
}

function drealty_lead_uri(DrealtyLead $lead) {
  return array('path' => 'drealty_lead/' . $lead->id);
}

function drealty_lead_block_info() {
	$blocks['drealty_lead_form'] = array(
    'info'   => t('dRealty Leads Listing Form'),
		'region' => -1,
    'cache'  => DRUPAL_NO_CACHE,
  );

	return $blocks;
}

function drealty_lead_block_view($delta = '') {
	if ($delta == 'drealty_lead_form') {
    $block['subject'] = isset($block['title']) ? $block['title'] : t('Request More Information');
    $block['content'] = drupal_get_form('drealty_lead_listing_form');
    return $block;
  }
}

function drealty_lead_load($id, $conditions = array(), $reset = FALSE) {
  $ids = (isset($id) ? array($id) : array());
  $entity = drealty_lead_load_multiple($ids, $conditions, $reset);
  return $entity ? reset($entity) : FALSE;
}

function drealty_lead_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('drealty_lead', $ids, $conditions, $reset);
}